#pragma once
// Shared Karnotation tables.
// Generated from karn.js by karnotation_gen.html
// Used by sq1opt.cpp (alg printing) and mainwindow.cpp (unkarnify / ergonomics rating).
// Edit this file once to affect both.
#include <string>
#include <map>
#include <set>

// ---------------------------------------------------------------------------
// KARN_TO_WCA  — Karnotation name (space-padded) → numeric WCA slash format
// ---------------------------------------------------------------------------
static const std::map<std::string,std::string> KARN_TO_WCA = {
    {" U4 ", " / U U' U U' / "},
    {" U4' ", " / U' U U' U / "},
    {" D4 ", " / D D' D D' / "},
    {" D4' ", " / D' D D' D / "},
    {" u4 ", " / u u' u u' / "},
    {" u4' ", " / u' u u' u / "},
    {" d4 ", " / d d' d d' / "},
    {" d4' ", " / d' d d' d / "},
    {" U3 ", " / U U' U / "},
    {" U3' ", " / U' U U' / "},
    {" D3 ", " / D D' D / "},
    {" D3' ", " / D' D D' / "},
    {" u3 ", " / u u' u / "},
    {" u3' ", " / u' u u' / "},
    {" d3 ", " / d d' d / "},
    {" d3' ", " / d' d d' / "},
    {" F3 ", " / F F' F / "},
    {" F3' ", " / F' F F' / "},
    {" f3 ", " / f f' f / "},
    {" f3' ", " / f' f f' / "},
    {" W ", " / U U' / "},
    {" W' ", " / U' U / "},
    {" B ", " / D D' / "},
    {" B' ", " / D' D / "},
    {" w ", " / u u' / "},
    {" w' ", " / u' u / "},
    {" b ", " / d d' / "},
    {" b' ", " / d' d / "},
    {" F2 ", " / F F' / "},
    {" F2' ", " / F' F / "},
    {" f2 ", " / f f' / "},
    {" f2' ", " / f' f / "},
    {" UU ", " / U U / "},
    {" UU' ", " / U' U' / "},
    {" DD ", " / D D / "},
    {" DD' ", " / D' D' / "},
    {" T2 ", " / T T' / "},
    {" T2' ", " / T' T / "},
    {" t2 ", " / t t' / "},
    {" t2' ", " / t' t / "},
    {" U2 ", " /6,0/ "},
    {" U2' ", " /6,0/ "},
    {" D2 ", " /0,6/ "},
    {" U2D ", " /6,3/ "},
    {" U2D' ", " /6,-3/ "},
    {" U2D2 ", " /6,6/ "},
    {" UD2 ", " /3,6/ "},
    {" U'D2 ", " /-3,6/ "},
    {" U ", " /3,0/ "},
    {" U' ", " /-3,0/ "},
    {" D ", " /0,3/ "},
    {" D' ", " /0,-3/ "},
    {" E ", " /3,-3/ "},
    {" E' ", " /-3,3/ "},
    {" e ", " /3,3/ "},
    {" e' ", " /-3,-3/ "},
    {" u ", " /2,-1/ "},
    {" u' ", " /-2,1/ "},
    {" d ", " /-1,2/ "},
    {" d' ", " /1,-2/ "},
    {" F ", " /4,1/ "},
    {" F' ", " /-4,-1/ "},
    {" f ", " /1,4/ "},
    {" f' ", " /-1,-4/ "},
    {" T ", " /2,-4/ "},
    {" T' ", " /-2,4/ "},
    {" t ", " /4,-2/ "},
    {" t' ", " /-4,2/ "},
    {" m ", " /2,2/ "},
    {" m' ", " /-2,-2/ "},
    {" M ", " /1,1/ "},
    {" M' ", " /-1,-1/ "},
    {" u2 ", " /5,-1/ "},
    {" u2' ", " /-5,1/ "},
    {" d2 ", " /-1,5/ "},
    {" d2' ", " /1,-5/ "},
    {" K ", " /5,2/ "},
    {" K' ", " /-5,-2/ "},
    {" k ", " /2,5/ "},
    {" k' ", " /-2,-5/ "},
    {" U2'D ", " /6,3/ "},
    {" U2'D' ", " /6,-3/ "},
    {" ɇ ", " / U D / "},
    {" ɇ' ", " / U' D' / "},
    {" Ɇ ", " / U D' / "},
    {" Ɇ' ", " / U' D / "},
};

// ---------------------------------------------------------------------------
// WCA_TO_KARN  — numeric WCA slash format (space-padded) → Karnotation name
// ---------------------------------------------------------------------------
static const std::map<std::string,std::string> WCA_TO_KARN = {
    {" U U' U U' ", " U4 "},
    {" U' U U' U ", " U4' "},
    {" D D' D D' ", " D4 "},
    {" D' D D' D ", " D4' "},
    {" u u' u u' ", " u4 "},
    {" u' u u' u ", " u4' "},
    {" d d' d d' ", " d4 "},
    {" d' d d' d ", " d4' "},
    {" U U' U ", " U3 "},
    {" U' U U' ", " U3' "},
    {" D D' D ", " D3 "},
    {" D' D D' ", " D3' "},
    {" u u' u ", " u3 "},
    {" u' u u' ", " u3' "},
    {" d d' d ", " d3 "},
    {" d' d d' ", " d3' "},
    {" F F' F ", " F3 "},
    {" F' F F' ", " F3' "},
    {" f f' f ", " f3 "},
    {" f' f f' ", " f3' "},
    {" U U' ", " W "},
    {" U' U ", " W' "},
    {" D D' ", " B "},
    {" D' D ", " B' "},
    {" u u' ", " w "},
    {" u' u ", " w' "},
    {" d d' ", " b "},
    {" d' d ", " b' "},
    {" F F' ", " F2 "},
    {" F' F ", " F2' "},
    {" f f' ", " f2 "},
    {" f' f ", " f2' "},
    {" U U ", " UU "},
    {" U' U' ", " UU' "},
    {" D D ", " DD "},
    {" D' D' ", " DD' "},
    {" 6,0 ", " U2 "},
    {" 6,3 ", " U2D "},
    {" 6,-3 ", " U2D' "},
    {" 6,6 ", " U2D2 "},
    {" 0,6 ", " D2 "},
    {" 3,6 ", " UD2 "},
    {" -3,6 ", " U'D2 "},
    {" 3,0 ", " U "},
    {" -3,0 ", " U' "},
    {" 0,3 ", " D "},
    {" 0,-3 ", " D' "},
    {" 3,-3 ", " E "},
    {" -3,3 ", " E' "},
    {" 3,3 ", " e "},
    {" -3,-3 ", " e' "},
    {" 2,-1 ", " u "},
    {" -2,1 ", " u' "},
    {" -1,2 ", " d "},
    {" 1,-2 ", " d' "},
    {" 4,1 ", " F "},
    {" -4,-1 ", " F' "},
    {" 1,4 ", " f "},
    {" -1,-4 ", " f' "},
    {" 2,-4 ", " T "},
    {" -2,4 ", " T' "},
    {" 4,-2 ", " t "},
    {" -4,2 ", " t' "},
    {" 2,2 ", " m "},
    {" -2,-2 ", " m' "},
    {" 1,1 ", " M "},
    {" -1,-1 ", " M' "},
    {" 5,-1 ", " u2 "},
    {" -5,1 ", " u2' "},
    {" -1,5 ", " d2 "},
    {" 1,-5 ", " d2' "},
    {" 5,2 ", " K "},
    {" -5,-2 ", " K' "},
    {" 2,5 ", " k "},
    {" -2,-5 ", " k' "},
};

// ---------------------------------------------------------------------------
// SHORTHAND_TO_KARN  — shorthand key (alignment-suffixed) → karn/numeric sequence
// ---------------------------------------------------------------------------
static const std::map<std::string,std::string> SHORTHAND_TO_KARN = {
    {"bjj", "/U' e D'/"},
    {"fjj", "/U e' D/"},
    {"e2bjj", "/U' e' U'/"},
    {"e2fjj", "/U e U/"},
    {"nn", "/E E'/"},
    {"jn", "/D4'/"},
    {"nj", "/U4/"},
    {"jj", "/U e' D/"},
    {"bjj+e2", "/U' e' U'/"},
    {"-nn", "/E' E/"},
    {"-jn", "/D4/"},
    {"-nj", "/D4'/"},
    {"bpj10", "/d m' U/"},
    {"bpj0-1", "/u' m D'/"},
    {"fpj10", "/u m' D/"},
    {"fpj0-1", "/d' m U'/"},
    {"aa10", "/u m' u T'/"},
    {"aa0-1", "/U m' U t'/"},
    {"fadj10", "/D M' d'/"},
    {"dadj10", "/D M' d'/"},
    {"fadj0-1", "/U' M u/"},
    {"u'adj0-1", "/U' M u/"},
    {"badj10", "/U M' u'/"},
    {"uadj10", "/U M' u'/"},
    {"badj0-1", "/D' M d/"},
    {"d'adj0-1", "/D' M d/"},
    {"bb10", "/T u' e U'/"},
    {"bb0-1", "/t d e' D/"},
    {"fdd10", "/D e' d t/"},
    {"fdd0-1", "/U' e u' T/"},
    {"bdd10", "/U e' u T'/"},
    {"bdd0-1", "/D' e d' t'/"},
    {"ff10", "/d m' d M E/"},
    {"ff0-1", "/u' m U' M T/"},
    {"fv10", "/d4/"},
    {"fv0-1", "/d4'/"},
    {"vf10", "/u4/"},
    {"vf0-1", "/u4'/"},
    {"y2fv10", "/u d' u -5,4/"},
    {"jf10", "/w D' u T'/"},
    {"jf0-1", "/w' D u' T/"},
    {"fj10", "/b U' d t/"},
    {"fj0-1", "/b' U d' t'/"},
    {"jr00", "/e' w e/"},
    {"jr10", "/e' b e/"},
    {"jr0-1", "/e' w' e/"},
    {"jr1-1", "/e' b' e/"},
    {"rj00", "/e b' e'/"},
    {"rj10", "/e w e'/"},
    {"rj0-1", "/e b' e'/"},
    {"rj1-1", "/e w e'/"},
    {"jv10", "/b D d d2'/"},
    {"jv0-1", "/b' D' d' d2/"},
    {"vj10", "/w U u u2'/"},
    {"vj0-1", "/w' U' u' u2/"},
    {"kk10", "/u m' U E'/"},
    {"kk0-1", "/U m' u E'/"},
    {"opp10", "/u2 u2'/"},
    {"opp0-1", "/u2' u2/"},
    {"pn10", "/T T'/"},
    {"pn0-1", "/t t'/"},
    {"px10", "/f' d3' f'/"},
    {"px0-1", "/f d3 f/"},
    {"xp10", "/F' u3' F'/"},
    {"xp0-1", "/F u3 F/"},
    {"tt10", "/d m' F' u2'/"},
    {"fss10", "/u M D' E'/"},
    {"fss0-1", "/D' M u E'/"},
    {"bss10", "/D M' u' E/"},
    {"bss0-1", "/U' M d E/"},
    {"vv10", "/u M u m' E'/"},
    {"zz10", "/u M t' M D'/"},
    {"zz0-1", "/D' M t' M u/"},
    {"30adj10", "/U M' u'/"},
    {"3adj10", "/U M' u'/"},
    {"03adj10", "/D M' d'/"},
    {"-30adj0-1", "/U' M u/"},
    {"obopp00", "1,0/M' F M' F M'/0,1"},
    {"oaopp1-1", "0,1/M' u' M' u' M'/0,1"},
    {"done!00", "0,0"},
};

// ---------------------------------------------------------------------------
// SHORTHAND_ALIGN_INDEPENDENT  — shorthands that don't need an alignment suffix
// ---------------------------------------------------------------------------
static const std::set<std::string> SHORTHAND_ALIGN_INDEPENDENT = {
    "bjj",
    "fjj",
    "nn",
    "jn",
    "nj",
    "e2bjj",
    "e2fjj",
    "jj",
    "bjj+e2",
    "-nn",
    "-jn",
    "-nj",
};

inline std::string trimStr(const std::string& s) {
    size_t a = s.find_first_not_of(" \t\r\n");
    if (a == std::string::npos) return "";
    size_t b = s.find_last_not_of(" \t\r\n");
    return s.substr(a, b - a + 1);
}

inline std::string replaceAll(std::string str, const std::string& from, const std::string& to) {
    size_t pos = 0;
    while ((pos = str.find(from, pos)) != std::string::npos) {
        str.replace(pos, from.size(), to);
        pos += to.size();
    }
    return str;
}

// ---------------------------------------------------------------------------
// dictReplace — repeatedly apply key→value map to str until stable
// ---------------------------------------------------------------------------
inline std::string dictReplace(std::string str, const std::map<std::string,std::string>& dict) {
    std::string prev;
    do {
        prev = str;
        for (const auto& [k, v] : dict)
            str = replaceAll(str, k, v);
    } while (str != prev);
    return str;
}
